# FlashDB is only supported by 32 bit architectures
FEATURES_REQUIRED_ANY += arch_32bit|arch_64bit
CFLAGS += -DFDB_USING_NATIVE_ASSERT

ifneq (,$(filter flashdb_tsdb,$(USEMODULE)))
  CFLAGS += -DFDB_USING_TSDB
endif

ifneq (,$(filter flashdb_kvdb_auto_update,$(USEMODULE)))
  CFLAGS += -DFDB_KV_AUTO_UPDATE
  USEMODULE += flashdb_kvdb
endif

ifneq (,$(filter flashdb_kvdb,$(USEMODULE)))
  CFLAGS += -DFDB_USING_KVDB
endif

ifneq (,$(filter flashdb_vfs,$(USEMODULE)))
  USEMODULE += vfs
endif

ifneq (,$(filter flashdb_mtd,$(USEMODULE)))
  CFLAGS += -DFDB_USING_FAL_MODE
  USEMODULE += flashdb_fal
  USEMODULE += mtd
else
  ifeq ($(CPU),native)
    CFLAGS += -DFDB_USING_FILE_POSIX_MODE
  else
    CFLAGS += -DFDB_USING_FILE_LIBC_MODE
    # The posix based file mode *should* also work on all
    # platforms if comiled with the posix_filesystem module.
    # Being able to switch between both may help with debugging
    # problems related to the file based storage and to avoid
    # inconsistencies between native and board behavior.
    #CFLAGS += -DFDB_USING_FILE_POSIX_MODE
    #USEMODULE += posix_filesystem
  endif
endif
